# Generated by Django 5.1.15 on 2026-10-03 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('first_visit_at', models.DateTimeField(blank=True, help_text='اولین نوبتی که مشتری گرفت', null=True, verbose_name='اولین بازدید')),
                ('last_visit_at', models.DateTimeField(blank=True, help_text='آخرین نوبت مشتری', null=True, verbose_name='آخرین بازدید')),
                ('visits_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نوبت\u200cها')),
                ('is_favorite', models.BooleanField(default=False, help_text='مشتری این کسب\u200cوکار رو نشون کرده', verbose_name='علاقه\u200cمندی')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت مشتری')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_customers', to='business.business', verbose_name='کسب\u200cوکار')),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='my_businesses', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'کسب\u200cوکار مشتری',
                'verbose_name_plural': 'کسب\u200cوکارهای مشتری',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='customers_c_custome_2a018f_idx'), models.Index(fields=['business', '-created_at'], name='customers_c_busines_56b128_idx'), models.Index(fields=['is_favorite'], name='customers_c_is_favo_1e44bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'business'), name='unique_customer_business')],
            },
        ),
    ]
