# Generated by Django 5.1.15 on 2026-10-03 05:39

import apps.accounts.managers
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(db_index=True, help_text='به فرمت 09XXXXXXXXX', max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('role', models.CharField(choices=[('customer', 'مشتری'), ('business_owner', 'صاحب کسب\u200cوکار'), ('admin', 'مدیر')], db_index=True, default='customer', max_length=20, verbose_name='نقش')),
                ('is_active', models.BooleanField(default=True, help_text='اگه False باشه، کاربر نمی\u200cتونه وارد بشه.', verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی به ادمین')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخرین IP ورود')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessOwnerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='business_owner_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('national_id', models.CharField(blank=True, help_text='برای احراز هویت (اختیاری)', max_length=10, verbose_name='کد ملی')),
            ],
            options={
                'verbose_name': 'پروفایل صاحب کسب\u200cوکار',
                'verbose_name_plural': 'پروفایل\u200cهای صاحب کسب\u200cوکار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='نام کامل')),
                ('hide_ads_banner', models.BooleanField(default=False, verbose_name='مخفی کردن بنر تبلیغاتی')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای داخلی (اختیاری)', verbose_name='یادداشت')),
            ],
            options={
                'verbose_name': 'پروفایل مشتری',
                'verbose_name_plural': 'پروفایل\u200cهای مشتری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=11, verbose_name='شماره موبایل')),
                ('code', models.CharField(max_length=10, verbose_name='کد')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='استفاده شده')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='تاریخ انقضا')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ استفاده')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
            ],
            options={
                'verbose_name': 'کد یک\u200cبارمصرف',
                'verbose_name_plural': 'کدهای یک\u200cبارمصرف',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'code', 'is_used'], name='accounts_ot_phone_c7b993_idx'), models.Index(fields=['expires_at'], name='accounts_ot_expires_2f08f4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
    ]
