# Generated by Django 5.1.15 on 2026-10-06 12:53

import apps.business.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='شناسه')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='آیکون')),
                ('is_salon', models.BooleanField(default=False, help_text='آیا این نوع فعالیت مخصوص سالن\u200cهاست؟', verbose_name='مخصوص سالن')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نوع فعالیت',
                'verbose_name_plural': 'انواع فعالیت',
                'ordering': ['is_salon', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('slug', models.SlugField(help_text='مثلاً: trial, basic, pro', unique=True, verbose_name='شناسه')),
                ('name', models.CharField(help_text='مثلاً: پلن پایه', max_length=50, verbose_name='نام')),
                ('icon', models.CharField(blank=True, default='⭐', help_text='مثلاً: 🎁 ⭐ 💎', max_length=10, verbose_name='آیکون')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='مدت (روز)')),
                ('features', models.JSONField(blank=True, default=list, help_text='لیست ویژگی\u200cها — مثال: ["نوبت\u200cدهی آنلاین", "QR Code"]', verbose_name='ویژگی\u200cها')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, help_text='اگه غیرفعال باشه، توی لیست خرید نشون داده نمیشه.', verbose_name='فعال')),
                ('is_paid', models.BooleanField(default=True, help_text='پلن\u200cهای رایگان (مثل trial) این فیلد رو False می\u200cکنن.', verbose_name='پولی')),
                ('has_pro_features', models.BooleanField(default=False, help_text='اگه True، امکانات pro فعالن.', verbose_name='ویژگی\u200cهای ویژه')),
            ],
            options={
                'verbose_name': 'پلن',
                'verbose_name_plural': 'پلن\u200cها',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('icon', models.CharField(blank=True, max_length=10, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مخاطب',
                'verbose_name_plural': 'مخاطبین',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('is_salon', models.BooleanField(db_index=True, default=False, verbose_name='سالن داره؟')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='شناسه لینک')),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='اسم صاحب کسب\u200cوکار')),
                ('landline', models.CharField(blank=True, max_length=15, verbose_name='تلفن ثابت')),
                ('region', models.CharField(db_index=True, max_length=100, verbose_name='منطقه')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='درباره ما')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='business/avatars/', validators=[apps.business.validators.validate_image], verbose_name='عکس پروفایل')),
                ('business_license', models.ImageField(blank=True, null=True, upload_to='business/licenses/', validators=[apps.business.validators.validate_image], verbose_name='عکس پروانه کسب')),
                ('entrance_photo', models.ImageField(blank=True, null=True, upload_to='business/entrances/', validators=[apps.business.validators.validate_image], verbose_name='عکس ورودی و تابلو')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='تأیید شده')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='رد شده')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد')),
                ('plan_expires_at', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضای پلن')),
                ('auto_confirm', models.BooleanField(default=False, verbose_name='تأیید خودکار نوبت\u200cها')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='business.activitytype', verbose_name='نوع فعالیت')),
                ('owner', models.OneToOneField(limit_choices_to={'role': 'business_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL, verbose_name='صاحب کسب\u200cوکار')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='business.plan', verbose_name='پلن')),
                ('target_audience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='business.targetaudience', verbose_name='مخاطب')),
            ],
            options={
                'verbose_name': 'کسب\u200cوکار',
                'verbose_name_plural': 'کسب\u200cوکارها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=100, verbose_name='نام خدمت')),
                ('duration', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)], verbose_name='مدت (دقیقه)')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='business.business', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='شماره موبایل')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='staff/avatars/', validators=[apps.business.validators.validate_image], verbose_name='عکس')),
                ('bio', models.TextField(blank=True, max_length=300, verbose_name='درباره')),
                ('is_owner', models.BooleanField(default=False, verbose_name='صاحب کسب\u200cوکار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='business.business', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('name', models.CharField(max_length=100, verbose_name='نام ایستگاه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='business.business', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'ایستگاه',
                'verbose_name_plural': 'ایستگاه\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('price', models.PositiveIntegerField(default=0, help_text='اگه ۰ باشه، از قیمت پیش\u200cفرض خدمت استفاده میشه.', verbose_name='قیمت اختصاصی (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='business.service', verbose_name='خدمت')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='business.staff', verbose_name='کارمند')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='business.station', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'خدمت کارمند',
                'verbose_name_plural': 'خدمات کارمند',
                'ordering': ['station', 'service', 'staff'],
            },
        ),
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('weekday', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='business.staff', verbose_name='کارمند')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_schedules', to='business.station', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'شیفت کارمند',
                'verbose_name_plural': 'شیفت\u200cهای کارمند',
                'ordering': ['station', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SpecialWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_hours', to='business.business', verbose_name='کسب\u200cوکار')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_hours', to='business.station', verbose_name='ایستگاه')),
            ],
            options={
                'verbose_name': 'ساعت کاری خاص',
                'verbose_name_plural': 'ساعت\u200cهای کاری خاص',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='business.station', verbose_name='ایستگاه'),
        ),
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ تعطیلی')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='business.business', verbose_name='کسب\u200cوکار')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='business.station', verbose_name='ایستگاه')),
            ],
            options={
                'verbose_name': 'روز تعطیل',
                'verbose_name_plural': 'روزهای تعطیل',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('start_time', models.TimeField(verbose_name='از ساعت')),
                ('end_time', models.TimeField(verbose_name='تا ساعت')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='عنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='business.business', verbose_name='کسب\u200cوکار')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='business.station', verbose_name='ایستگاه')),
            ],
            options={
                'verbose_name': 'وقفه استراحت',
                'verbose_name_plural': 'وقفه\u200cهای استراحت',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('weekday', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='business.business', verbose_name='کسب\u200cوکار')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='business.station', verbose_name='ایستگاه')),
            ],
            options={
                'verbose_name': 'برنامه هفتگی',
                'verbose_name_plural': 'برنامه\u200cهای هفتگی',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('method', models.CharField(choices=[('card_to_card', 'کارت به کارت'), ('gateway', 'درگاه پرداخت')], default='card_to_card', max_length=20, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=10, verbose_name='وضعیت')),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='payments/receipts/', validators=[apps.business.validators.validate_image], verbose_name='عکس رسید')),
                ('tracking_code', models.CharField(blank=True, max_length=50, verbose_name='کد پیگیری')),
                ('customer_note', models.TextField(blank=True, max_length=500, verbose_name='یادداشت مشتری')),
                ('admin_note', models.TextField(blank=True, max_length=500, verbose_name='یادداشت ادمین')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='business.business', verbose_name='کسب\u200cوکار')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='business.plan', verbose_name='پلن')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='business_pa_busines_c662ba_idx'), models.Index(fields=['status', 'created_at'], name='business_pa_status_c59197_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('object_id', models.PositiveIntegerField(verbose_name='شناسه')),
                ('field_name', models.CharField(choices=[('name', 'نام'), ('address', 'آدرس'), ('region', 'منطقه'), ('bio', 'درباره ما'), ('avatar', 'عکس پروفایل'), ('business_license', 'پروانه کسب'), ('entrance_photo', 'عکس ورودی')], max_length=30, verbose_name='فیلد مورد تغییر')),
                ('old_value_text', models.TextField(blank=True, verbose_name='مقدار قبلی (متنی)')),
                ('new_value_text', models.TextField(blank=True, verbose_name='مقدار جدید (متنی)')),
                ('new_value_file', models.FileField(blank=True, null=True, upload_to='business/change_requests/', verbose_name='فایل جدید')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=10, verbose_name='وضعیت')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='business.business', verbose_name='کسب\u200cوکار')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع مدل')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_changes', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
            ],
            options={
                'verbose_name': 'درخواست تغییر',
                'verbose_name_plural': 'درخواست\u200cهای تغییر',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='business_pr_busines_fdd6cb_idx'), models.Index(fields=['status', 'created_at'], name='business_pr_status_80e475_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(condition=models.Q(('is_owner', True)), fields=('business',), name='unique_owner_per_business'),
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('business', 'name')},
        ),
        migrations.AddIndex(
            model_name='staffservice',
            index=models.Index(fields=['service', 'is_active'], name='business_st_service_277cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='staffservice',
            index=models.Index(fields=['staff', 'is_active'], name='business_st_staff_i_74f788_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffservice',
            constraint=models.UniqueConstraint(fields=('staff', 'service', 'station'), name='unique_staff_service_station'),
        ),
        migrations.AddIndex(
            model_name='staffschedule',
            index=models.Index(fields=['station', 'weekday'], name='business_st_station_dcdf10_idx'),
        ),
        migrations.AddIndex(
            model_name='staffschedule',
            index=models.Index(fields=['staff', 'weekday'], name='business_st_staff_i_14a21a_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffschedule',
            constraint=models.UniqueConstraint(fields=('staff', 'station', 'weekday', 'start_time'), name='unique_staff_station_weekday_start'),
        ),
        migrations.AddConstraint(
            model_name='specialworkinghours',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', False)), fields=('business', 'station', 'date'), name='unique_special_hours_with_station'),
        ),
        migrations.AddConstraint(
            model_name='specialworkinghours',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', True)), fields=('business', 'date'), name='unique_special_hours_no_station'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('business', 'station', 'name')},
        ),
        migrations.AddConstraint(
            model_name='dayoff',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', False)), fields=('business', 'station', 'date'), name='unique_day_off_with_station'),
        ),
        migrations.AddConstraint(
            model_name='dayoff',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', True)), fields=('business', 'date'), name='unique_day_off_no_station'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_active', 'region'], name='business_bu_is_acti_041116_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_active', 'is_salon'], name='business_bu_is_acti_0a1204_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['-created_at'], name='business_bu_created_69feca_idx'),
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', False)), fields=('business', 'station', 'weekday'), name='unique_working_hours_with_station'),
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', True)), fields=('business', 'weekday'), name='unique_working_hours_no_station'),
        ),
    ]
