# Generated by Django 5.1.15 on 2026-10-03 08:48

import apps.business.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('plan', models.CharField(choices=[('trial', 'دوره تست'), ('basic', 'پایه'), ('pro', 'ویژه')], max_length=10, verbose_name='پلن')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('method', models.CharField(choices=[('card_to_card', 'کارت به کارت'), ('gateway', 'درگاه پرداخت')], default='card_to_card', max_length=20, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=10, verbose_name='وضعیت')),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='payments/receipts/', validators=[apps.business.validators.validate_image], verbose_name='عکس رسید')),
                ('tracking_code', models.CharField(blank=True, help_text='شماره پیگیری تراکنش', max_length=50, verbose_name='کد پیگیری')),
                ('customer_note', models.TextField(blank=True, max_length=500, verbose_name='یادداشت مشتری')),
                ('admin_note', models.TextField(blank=True, max_length=500, verbose_name='یادداشت ادمین')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='business.business', verbose_name='کسب\u200cوکار')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='business_pa_busines_c662ba_idx'), models.Index(fields=['status', 'created_at'], name='business_pa_status_c59197_idx')],
            },
        ),
    ]
