# Generated by Django 5.1.15 on 2026-10-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_payment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dayoff',
            name='unique_business_station_day_off',
        ),
        migrations.RemoveConstraint(
            model_name='specialworkinghours',
            name='unique_business_station_special_hours',
        ),
        migrations.RemoveConstraint(
            model_name='workinghours',
            name='unique_business_station_weekday',
        ),
        migrations.AddConstraint(
            model_name='dayoff',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', False)), fields=('business', 'station', 'date'), name='unique_day_off_with_station'),
        ),
        migrations.AddConstraint(
            model_name='dayoff',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', True)), fields=('business', 'date'), name='unique_day_off_no_station'),
        ),
        migrations.AddConstraint(
            model_name='specialworkinghours',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', False)), fields=('business', 'station', 'date'), name='unique_special_hours_with_station'),
        ),
        migrations.AddConstraint(
            model_name='specialworkinghours',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', True)), fields=('business', 'date'), name='unique_special_hours_no_station'),
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', False)), fields=('business', 'station', 'weekday'), name='unique_working_hours_with_station'),
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', True)), fields=('business', 'weekday'), name='unique_working_hours_no_station'),
        ),
    ]
