# Generated by Django 5.1.15 on 2026-10-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_dayoff_unique_business_station_day_off_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('slug', models.SlugField(help_text='مثلاً: trial, basic, pro', unique=True, verbose_name='شناسه')),
                ('name', models.CharField(help_text='مثلاً: پلن پایه', max_length=50, verbose_name='نام')),
                ('icon', models.CharField(blank=True, default='⭐', help_text='مثلاً: 🎁 ⭐ 💎', max_length=10, verbose_name='آیکون')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='مدت (روز)')),
                ('features', models.JSONField(blank=True, default=list, help_text='لیست ویژگی\u200cها — مثال: ["نوبت\u200cدهی آنلاین", "QR Code"]', verbose_name='ویژگی\u200cها')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, help_text='اگه غیرفعال باشه، توی لیست خرید نشون داده نمیشه.', verbose_name='فعال')),
                ('is_paid', models.BooleanField(default=True, help_text='پلن\u200cهای رایگان (مثل trial) این فیلد رو False می\u200cکنن.', verbose_name='پولی')),
                ('has_pro_features', models.BooleanField(default=False, help_text='اگه True، امکانات pro (یادآور، لیست انتظار، ...) فعالن.', verbose_name='ویژگی\u200cهای ویژه')),
            ],
            options={
                'verbose_name': 'پلن',
                'verbose_name_plural': 'پلن\u200cها',
                'ordering': ['order', 'price'],
            },
        ),
    ]
