# Generated by Django 5.1.15 on 2026-10-04 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_seed_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='business.plan', verbose_name='پلن فعلی'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='business.plan', verbose_name='پلن'),
        ),
    ]
