# Generated by Django 5.1.15 on 2026-10-04 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_make_plan_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('weekday', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='business.staff', verbose_name='کارمند')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_schedules', to='business.station', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'شیفت کارمند',
                'verbose_name_plural': 'شیفت\u200cهای کارمند',
                'ordering': ['station', 'weekday', 'start_time'],
                'indexes': [models.Index(fields=['station', 'weekday'], name='business_st_station_dcdf10_idx'), models.Index(fields=['staff', 'weekday'], name='business_st_staff_i_14a21a_idx')],
                'constraints': [models.UniqueConstraint(fields=('staff', 'station', 'weekday', 'start_time'), name='unique_staff_station_weekday_start')],
            },
        ),
    ]
