# Generated by Django 5.1.15 on 2026-10-04 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_add_staff_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('price', models.PositiveIntegerField(default=0, help_text='اگه ۰ باشه، از قیمت پیش\u200cفرض خدمت استفاده میشه.', verbose_name='قیمت اختصاصی (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='business.service', verbose_name='خدمت')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='business.staff', verbose_name='کارمند')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='business.station', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'خدمت کارمند',
                'verbose_name_plural': 'خدمات کارمند',
                'ordering': ['station', 'service', 'staff'],
                'indexes': [models.Index(fields=['service', 'is_active'], name='business_st_service_277cbf_idx'), models.Index(fields=['staff', 'is_active'], name='business_st_staff_i_74f788_idx')],
                'constraints': [models.UniqueConstraint(fields=('staff', 'service', 'station'), name='unique_staff_service_station')],
            },
        ),
    ]
