# Generated by Django 5.1.15 on 2026-10-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_migrate_staff_members_to_staff_service'),
    ]

    operations = [
    ]
