# Generated by Django 5.1.15 on 2026-10-04 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_migrate_staff_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='staff_members',
        ),
        migrations.RemoveField(
            model_name='station',
            name='staff_members',
        ),
        migrations.AlterField(
            model_name='business',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='business.plan', verbose_name='پلن'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='business.plan', verbose_name='پلن'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_pro_features',
            field=models.BooleanField(default=False, help_text='اگه True، امکانات pro فعالن.', verbose_name='ویژگی\u200cهای ویژه'),
        ),
    ]
