# Generated by Django 5.1.15 on 2026-10-04 11:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('category', models.CharField(choices=[('technical', 'مشکل فنی'), ('payment', 'پرداخت و پلن'), ('booking', 'نوبت\u200cدهی'), ('complaint', 'شکایت'), ('suggestion', 'پیشنهاد'), ('other', 'سایر')], db_index=True, default='other', max_length=20, verbose_name='دسته')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], db_index=True, default='normal', max_length=10, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال بررسی'), ('answered', 'پاسخ داده شده'), ('closed', 'بسته شده')], db_index=True, default='open', max_length=15, verbose_name='وضعیت')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بسته شدن')),
                ('last_reply_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='آخرین پاسخ')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت\u200cها',
                'ordering': ['-last_reply_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('message', models.TextField(max_length=2000, verbose_name='متن پیام')),
                ('is_staff_reply', models.BooleanField(db_index=True, default=False, verbose_name='پاسخ ادمین')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='خوانده شده')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket', verbose_name='تیکت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'پیام تیکت',
                'verbose_name_plural': 'پیام\u200cهای تیکت',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('file', models.FileField(upload_to='tickets/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'pdf'])], verbose_name='فایل')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='نام اصلی')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم (بایت)')),
                ('ticket_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.ticketmessage', verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'فایل پیوست',
                'verbose_name_plural': 'فایل\u200cهای پیوست',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', 'status'], name='support_tic_user_id_bbc719_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-created_at'], name='support_tic_status_a78228_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'status'], name='support_tic_assigne_6ed26f_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='support_tic_ticket__0cd9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['is_read', 'is_staff_reply'], name='support_tic_is_read_8e04d9_idx'),
        ),
    ]
