# Generated by Django 5.1.15 on 2026-10-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('service_name_snapshot', models.CharField(help_text='در زمان رزرو ذخیره میشه', max_length=100, verbose_name='نام خدمت (snapshot)')),
                ('service_price_snapshot', models.PositiveIntegerField(default=0, verbose_name='قیمت خدمت (snapshot)')),
                ('service_duration_snapshot', models.PositiveIntegerField(default=30, help_text='دقیقه', verbose_name='مدت خدمت (snapshot)')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='زمان شروع')),
                ('end_at', models.DateTimeField(db_index=True, verbose_name='زمان پایان')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('cancelled', 'لغو شده'), ('completed', 'انجام شده'), ('no_show', 'عدم حضور')], db_index=True, default='pending', max_length=15, verbose_name='وضعیت')),
                ('customer_note', models.TextField(blank=True, max_length=500, verbose_name='یادداشت مشتری')),
                ('owner_note', models.TextField(blank=True, max_length=500, verbose_name='یادداشت کسب\u200cوکار')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
                ('cancellation_reason', models.TextField(blank=True, max_length=500, verbose_name='دلیل لغو')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('phone', models.CharField(db_index=True, max_length=11, verbose_name='شماره موبایل')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='نام')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل')),
            ],
            options={
                'verbose_name': 'مشتری بلاک\u200cشده',
                'verbose_name_plural': 'مشتری\u200cهای بلاک\u200cشده',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('service_name_snapshot', models.CharField(max_length=100, verbose_name='نام خدمت (snapshot)')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ مورد نظر')),
                ('preferred_time', models.TimeField(blank=True, null=True, verbose_name='ساعت ترجیحی')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='یادداشت')),
                ('status', models.CharField(choices=[('waiting', 'در انتظار'), ('notified', 'اطلاع داده شده'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده'), ('converted', 'تبدیل به نوبت')], db_index=True, default='waiting', max_length=15, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'لیست انتظار',
                'verbose_name_plural': 'لیست\u200cهای انتظار',
                'ordering': ['date', 'preferred_time', 'created_at'],
            },
        ),
    ]
