# Generated by Django 5.1.15 on 2026-10-03 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='business.business', verbose_name='کسب\u200cوکار'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL, verbose_name='لغوکننده'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='اگه دستی ثبت شده، ادمین کسب\u200cوکار', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='business.service', verbose_name='خدمت'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='business.station', verbose_name='ایستگاه'),
        ),
        migrations.AddField(
            model_name='blockedcustomer',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_customers', to='business.business', verbose_name='کسب\u200cوکار'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='business.business', verbose_name='کسب\u200cوکار'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_list', to='business.service', verbose_name='خدمت'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['business', 'start_at'], name='booking_app_busines_fce0aa_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['business', 'status', 'start_at'], name='booking_app_busines_fa0fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['customer', 'start_at'], name='booking_app_custome_bf268c_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'start_at'], name='booking_app_status_447b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['start_at', 'end_at'], name='booking_app_start_a_f456de_idx'),
        ),
        migrations.AddConstraint(
            model_name='blockedcustomer',
            constraint=models.UniqueConstraint(fields=('business', 'phone'), name='unique_blocked_business_phone'),
        ),
        migrations.AddIndex(
            model_name='waitinglist',
            index=models.Index(fields=['business', 'status', 'date'], name='booking_wai_busines_d2de9a_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglist',
            index=models.Index(fields=['customer', 'status'], name='booking_wai_custome_a97225_idx'),
        ),
    ]
