# Generated by Django 5.1.15 on 2026-10-03 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_appointment_staff_and_more'),
        ('business', '0003_remove_dayoff_unique_business_station_day_off_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('staff__isnull', False), ('status__in', ['pending', 'confirmed'])), fields=('staff', 'start_at'), name='unique_active_appointment_per_staff'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', False), ('status__in', ['pending', 'confirmed'])), fields=('station', 'start_at'), name='unique_active_appointment_per_station'),
        ),
    ]
