# Generated by Django 5.1.15 on 2026-10-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('phone', models.CharField(db_index=True, max_length=11, verbose_name='شماره موبایل')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('sms_type', models.CharField(choices=[('otp', 'کد ورود'), ('booking_confirm', 'تأیید نوبت'), ('booking_cancel', 'لغو نوبت'), ('booking_reminder', 'یادآور نوبت'), ('waiting_list', 'لیست انتظار'), ('welcome', 'خوش\u200cآمد'), ('other', 'سایر')], db_index=True, default='other', max_length=20, verbose_name='نوع')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('sent', 'ارسال شده'), ('failed', 'ناموفق'), ('delivered', 'تحویل داده شده')], db_index=True, default='pending', max_length=15, verbose_name='وضعیت')),
                ('backend', models.CharField(blank=True, max_length=50, verbose_name='سرویس\u200cدهنده')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه پیام (سرویس\u200cدهنده)')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
            ],
            options={
                'verbose_name': 'لاگ SMS',
                'verbose_name_plural': 'لاگ\u200cهای SMS',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', '-created_at'], name='notificatio_phone_9da666_idx'), models.Index(fields=['sms_type', '-created_at'], name='notificatio_sms_typ_3f426d_idx'), models.Index(fields=['status', '-created_at'], name='notificatio_status_26111a_idx')],
            },
        ),
    ]
